manuf/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from xadmin.plugins import xversion
import xadmin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    
    #url(r'app01/', include('app01.urls')),
    url(r'^', include('web.urls')),
    url(r'^', include('mould.urls')),
    url(r'^', include('welding.urls')),
    url(r'^', include('testing.urls')),
    url(r'^', include('app01.urls')),
    path('xadmin/', xadmin.site.urls),

]+ static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

web/urls.py
from django.conf.urls import url
from django.conf import settings
from mould.views.resume import resume
from web.views import account, home, project, wiki, file, setting, issues, dashboard, statistics
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    url(r'^register/$', account.register, name='register'),
    url(r'^send/sms/$', account.send_sms, name='send_sms'),
    url(r'^login/$', account.login, name='login'),
    url(r'^account/change/name', account.change_name, name='changename'),
    url(r'^account/changepwd', account.change_pwd, name='changepwd'),
    url(r'^logout/', account.logout, name='logout'),
    url(r'^image/code/', account.image_code, name='image_code'),
    path('', home.index, name='index'),  # 默认首页

    # 项目列表
    url(r'^project/list/', project.project_list, name='project_list'),
    url(r'^project/star/(?P<project_type>\w+)/(?P<project_id>\d+)/$',
        project.project_star, name='project_star'),
    url(r'^project/unstar/(?P<project_type>\w+)/(?P<project_id>\d+)/$',
        project.project_unstar, name='project_unstar'),


    # 项目管理
    # 路由分发
    url(r'^manage/(?P<project_id>\d+)/', include([

        url(r'^wiki/$', wiki.wiki, name='wiki'),
        url(r'^wiki/add/$', wiki.wiki_add, name='wiki_add'),
        url(r'^wiki/delete/(?P<wiki_id>\d+)/$',
            wiki.wiki_delete, name='wiki_delete'),
        url(r'^wiki/edit/(?P<wiki_id>\d+)/$', wiki.wiki_edit, name='wiki_edit'),
        url(r'^wiki/upload/', wiki.wiki_upload, name='wiki_upload'),
        url(r'^wiki/catalog/', wiki.wiki_catalog, name='wiki_catalog'),

        url(r'^file/$', file.file, name='file'),
        url(r'^file/delete/$', file.file_delete, name='file_delete'),
        url(r'^cos/credential/$', file.cos_credential, name='cos_credential'),
        url(r'^file/post/$', file.file_post, name='file_post'),
        url(r'^file/download/(?P<file_id>\d+)/$',
            file.file_download, name='file_download'),

        url(r'^setting/$', setting.setting, name='setting'),
        url(r'^setting/delete/$', setting.setting_delete, name='setting_delete'),

        url(r'^issues/$', issues.issues, name='issues'),
        url(r'^issues/detail/(?P<issues_id>\d+)/$',
            issues.issues_detail, name='issues_detail'),
        url(r'^issues/record/(?P<issues_id>\d+)/$',
            issues.issues_record, name='issues_record'),
        url(r'^issues/change/(?P<issues_id>\d+)/$',
            issues.issues_change, name='issues_change'),
        url(r'^issues/invite/url/$', issues.invite_url, name='invite_url'),

        url(r'^dashboard/$', dashboard.dashboard, name='dashboard'),
        url(r'^dashboard/issues/chart/$',
            dashboard.issues_chart, name='issues_chart'),

        url(r'^statistics/$', statistics.statistics, name='statistics'),
        url(r'^statistics/priority/$', statistics.statistics_priority,
            name='statistics_priority'),
        url(r'^statistics/project/user/$',
            statistics.statistics_project_user, name='statistics_project_user'),

    ], None)),
]

welding/urls.py
from django.conf.urls import url, include
from welding.views import wsearch
urlpatterns = [
    url(r'^wsearch/$', wsearch.wsearch, name='wsearch'),
    url(r'^wsearch/r/(?P<recipe_id>\d+)/$', wsearch.r, name='wsearch_r'),
    url(r'^wsearch/p/$', wsearch.p, name='wsearch_p'),


    # 路由分发


]

welding/models.py
from typing import TYPE_CHECKING
from django.db import models
from datetime import datetime
# Create your models here.


class Parameters(models.Model):
    SERIAL_CHOICES = (
        ('1', 'B-1'),
        ('2', 'B-2'),
        ('3', 'B-3'),
        ('4', 'B-4'),
        ('5', 'B-5'),
        ('6', 'B-6'),
        ('7', 'B-7'),
        ('8', 'B-8'),
        ('9', 'B-9'),
        ('A', 'B-A'),
        ('B', 'B-B'),
        ('C', 'B-C'),
        ('D', 'B-D'),
        ('E', 'B-E'),
        ('F', 'B-F'),
    )
    ETYPE_CHOICES=(
        ('1', '上I下I'),
        ('2', '上L下I'),
        ('3', '上I下L'),
        ('4', '上L下L'),
        ('5', '其它'),

    )

    line= models.CharField(
        max_length=20, blank=True, null=True, verbose_name="线别")
    equipment = models.CharField(
        max_length=20, blank=True, null=True, verbose_name="设备")
    eq_model = models.CharField(
        max_length=20, blank=True, null=True, verbose_name="设备")
    serial = models.CharField(max_length=3, blank=True,
                              null=True, choices=SERIAL_CHOICES, verbose_name="系列")
    etype = models.CharField(max_length=3, blank=True,
                              null=True, choices=ETYPE_CHOICES, verbose_name="握杆式样")
    Prsquez = models.CharField(
        max_length=3, blank=True, null=True, verbose_name="预压")
    squeeze = models.CharField(
        max_length=3, blank=True, null=True, verbose_name="加压")
    slope = models.CharField(max_length=3, blank=True,
                             null=True, verbose_name="缓升")
    weld1 = models.CharField(max_length=3, blank=True,
                             null=True, verbose_name="通电1")
    cool1 = models.CharField(max_length=3, blank=True,
                             null=True, verbose_name="冷却1")
    weld2 = models.CharField(max_length=3, blank=True,
                             null=True, verbose_name="通电2")
    cool2 = models.CharField(max_length=3, blank=True,
                             null=True, verbose_name="冷却2")
    weld3 = models.CharField(max_length=3, blank=True,
                             null=True, verbose_name="通电3")
    dslope = models.CharField(max_length=3, blank=True,
                              null=True, verbose_name="缓降")
    hold = models.CharField(max_length=3, blank=True,
                            null=True, verbose_name="保持")
    heat1 = models.CharField(max_length=3, blank=True,
                             null=True, verbose_name="焊接1")
    heat2 = models.CharField(max_length=3, blank=True,
                             null=True, verbose_name="焊接2")
    heat3 = models.CharField(max_length=3, blank=True,
                             null=True, verbose_name="焊接3")
    TurnR = models.CharField(max_length=3, blank=True,
                             null=True, verbose_name="匝数比")
    GunSel= models.CharField(max_length=3, blank=True,
                             null=True, verbose_name="钳选择")
    gauge = models.CharField(max_length=3, blank=True,
                             null=True, verbose_name="表压力")
    pressure = models.CharField(
        max_length=3, blank=True, null=True, verbose_name="加压力")
    

    class Meta:
        db_table = "w_parameters"


class Recipe(models.Model):

    item = models.CharField(max_length=20, blank=True,
                            null=True, verbose_name="项目")
    part_no = models.CharField(
        max_length=20, blank=True, null=True, verbose_name="零件号")
    op = models.CharField(max_length=20, blank=True,
                          null=True, verbose_name="工序")
    name = models.CharField(max_length=20, blank=True,
                            null=True, verbose_name="名称")

    m1 = models.CharField(max_length=20, blank=True,
                          null=True, verbose_name="材料1")
    t1 = models.CharField(max_length=20, blank=True,
                          null=True, verbose_name="厚度1")
    m2 = models.CharField(max_length=20, blank=True,
                          null=True, verbose_name="材料2")
    t2 = models.CharField(max_length=20, blank=True,
                          null=True, verbose_name="厚度2")
    m3 = models.CharField(max_length=20, blank=True,
                          null=True, verbose_name="材料3")
    t3 = models.CharField(max_length=20, blank=True,
                          null=True, verbose_name="厚度3")
    diameter = models.CharField(
        max_length=20, blank=True, null=True, verbose_name="修磨直径（mm)")
    spots = models.CharField(
        max_length=5, blank=True, null=True, verbose_name="打点数")
    imgs = models.ImageField(blank=True, null=True, verbose_name="图片")
    remark = models.CharField(
        max_length=100, blank=True, null=True, verbose_name="备注")
    frequency = models.CharField(
        max_length=20, blank=True, null=True, verbose_name="修磨频次")
    modify = models.ForeignKey(blank=False, null=True, default='1',
                               to='web.UserInfo', on_delete=models.CASCADE, verbose_name="修改者")
    modify_time = models.DateTimeField(auto_now_add=True, verbose_name="修改时间")
    sc = models.ManyToManyField(to='Parameters', verbose_name="参数")

    def __str__(self):
        return "%s-%s" % (self.part_no, self.op)

    class Meta:
        db_table = "w_recipe"

welding/views/wsearch.py
from django.db.models.expressions import Value
from web import models
from django.shortcuts import render
import datetime
import time

from django.http import JsonResponse
import collections
import rander as rander

from welding.models import Parameters, Recipe
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from helpers import get_page_list, ajax_required
from utils.pagination import Pagination
from django.db.models import Q


def wsearch(request):

    if request.method == 'POST':
        return render(request, 'web/index.html')

    Ae = request.GET.get('equipment')

    A2 = request.GET.get('part_no')

    if Ae:
        eqs = Parameters.objects.filter(equipment__contains=Ae).values(
            'equipment').distinct().order_by('equipment')
        print(eqs)
        count = eqs.count()
        if count == 0:
            error_msg = "抱歉！没有找到查询结果!"
            print(locals())
            return render(request, 'welding/search_result.html', locals())
        eqsl = []
        for e in eqs:
            print(e)
            s = e['equipment']
            print(s)
            eqsl.append(Parameters.objects.filter(equipment=s).first())
        page_object = Pagination(
            current_page=request.GET.get('page'),
            all_count=len(eqsl),
            base_url=request.path_info,
            query_params=request.GET,
            per_page=12,
            pager_page_count=7,

        )
        print(eqsl)

        eq_object_list = eqs[page_object.start:page_object.end]

        context = {

            'eq': eqsl,
            'page_html': page_object.page_html(),
            'count': count
        }
        return render(request, 'welding/search_result.html', context)

    if A2:
        print("A2")
        search_result = Recipe.objects.filter(part_no__contains=A2)
        count = search_result.count()
        if count == 0:
            error_msg = "抱歉！没有找到查询结果!"
            print(locals())
            return render(request, 'welding/search_result.html', locals())
        page_object = Pagination(
            current_page=request.GET.get('page'),
            all_count=search_result.count(),
            base_url=request.path_info,
            query_params=request.GET,
            per_page=12,
            pager_page_count=7,

        )

        welding_object_list = search_result[page_object.start:page_object.end]

        context = {

            'search_result': welding_object_list,
            'page_html': page_object.page_html(),
            'count': count
        }
        return render(request, 'welding/search_result.html', context)

    error_msg = "出错了！没有找到查询结果，请输入正确的信息"
    print(locals())
    return render(request, 'welding/search_result.html', locals())
# Create your views here.


def r(request, recipe_id):
    if request.method == 'POST':
        return render(request, 'web/index.html')

    recipe_result = Recipe.objects.filter(id=recipe_id).first

    search_result = Parameters.objects.filter(recipe__id=recipe_id)
    count = search_result.count()
    if count == 0:
        error_msg = "抱歉！没有找到查询结果!"
        print(locals())
        return render(request, 'welding/search_r.html', locals())
    page_object = Pagination(
        current_page=request.GET.get('page'),
        all_count=search_result.count(),
        base_url=request.path_info,
        query_params=request.GET,
        per_page=12,
        pager_page_count=7,

    )

    r_search_result = search_result[page_object.start:page_object.end]

    context = {
        'sr': recipe_result,
        'search_result': r_search_result,
        'page_html': page_object.page_html(),
        'count': count
    }

    return render(request, 'welding/search_r.html', context)


def p(request):
    if request.method == 'POST':
        return render(request, 'web/index.html')
    pass
    context = {
        
    }

    return render(request, 'welding/search_p.html',context)

welding/templates/welding/search_p.html
{% extends 'layout/basic.html' %} {% load static %} {% block title %} 首页 
{% endblock %} {% block css %}
<link
  rel="stylesheet"
  href="{% static 'web/plugin/bootstrap/css/bootstrap.css' %}"
/>
<link rel="stylesheet" href="{% static 'web/css/carousel.css' %}" />

{% endblock %} {% block content %}
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

  {% if error_msg %}<div class= "text-center"> {{ error_msg }} </div>
  {% else %}
  {% if request.web.user %}


  {% else %}
                    <div class="bs-example bs-example-standalone" data-example-id="dismissible-alert-js">
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
      <strong><h4>登录警告</h4></strong>
      <p>查看具体参数及产品信息须登录账户方可查询。
      <a target="_blank" href="{% url 'login'  %}"
          >登录</a></p>
        </div>
  {% endif %}
          <div class="container-fluid">
<table class="table table-bordered text-center">
        <thead>
        <tr>
        
        <th class= 'active text-center'>零件号</th>
        <th class= 'text-center'>工序</th>
        <th class= 'success text-center'>焊接内容</th>
        <th class= 'text-center'>打点数</th>
        <th class= 'info text-center'>图示</th>
        <th class= 'text-center'>焊接设备</th>
        </tr>
        </thead>
        {% for ps in part_result %}
        <tr>
      <td class= 'active '>{{ ps.part_no }}</td>
      <td>{{ ps.op }}</td>
      <td class= 'success'>{{ps.m1}}{{sr.t1}}+{{ps.m2}}{{ps.t2}}+{{ps.m3}}{{ps.t3}}</td>
      <td>{{ ps.spots }}</td>
      <td class= 'info' align="center" valign="middle" >
      <a target="_blank"href="{{ ps.imgs }}"><img src="{{ ps.imgs }}" style="height: 60px"></a></td>
      <a href="{% url 'wsearch/r/' recipe_id=ps.id %}">设备</a>
      {% endfor %}
      
</div>

</table>


<div class= "text-center">
<h3>查询结果<span class="label badge">{{count}}</span></h3>
</div>
<div class="container-fluid">
    <table class="table table-bordered text-center">
    <thead>
      <tr>
        <th class= 'text-center'>设备编号</th>
        <th class= 'warning text-center'>系列</th>
      </tr>
    </thead>
    {% for sr in search_result %}
    <tr>
      
           
      <td >
        <a target="_blank" href="#"
          >{{ sr.equipment }}</a>
      </td>
      <td class = 'warning'>
        <a href="{% url 'r_parts' tool_id=sr.id %}"
          >{{ sr.serial }}</a>
      </td>
    </tr>

    {% endfor %}


  </table>

  </div>
  <hr style="border-top:1px dashed #987cb9;" width="100%" color="#987cb9" size=1>

  </div>
</div >
  {% endif %}
<nav style="text-align: center;" aria-label="...">
                <ul class="pagination" style="margin-top: 0px">
                    {{ page_html|safe }}
                </ul>
            </nav>
</div>

{% endblock %}

welding/templates/welding/search_r.html
{% extends 'layout/basic.html' %} {% load static %} 
{% block title %} 零件参数查询 
{% endblock %} 
{% block css %}
<link
  rel="stylesheet"
  href="{% static 'web/plugin/bootstrap/css/bootstrap.css' %}"
/>
<link rel="stylesheet" href="{% static 'web/css/carousel.css' %}" />
{% endblock %}
{% block content %}
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  {% if error_msg %}<div class= "text-center"> {{ error_msg }} </div>
  {% else %}
  {% if request.web.user %}


  {% else %}
                    <div class="bs-example bs-example-standalone" data-example-id="dismissible-alert-js">
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
      <strong><h4>登录警告</h4></strong>
      <p>查看具体参数及产品信息须登录账户方可查询。
      <a target="_blank" href="{% url 'login'  %}"
          >登录</a></p>
        </div>
  {% endif %}
  <div class="container-fluid">
  <table class="table table-bordered text-center">
        <thead>
        <tr>
        
        <th class= 'active text-center'>零件号</th>
        <th class= 'text-center'>工序</th>
        <th class= 'success text-center'>焊接内容</th>
        <th class= 'text-center'>打点数</th>
        <th class= 'text-center'>研磨端径</th>
        <th class= 'info text-center'>图示</th>
        
        </tr>
        </thead>
        
        <tr>

    <tr>
      <td class= 'active '>{{ sr.part_no }}</td>
      <td>{{ sr.op }}</td>
      <td class= 'success '>{{sr.m1}}{{sr.t1}}+{{sr.m2|default_if_none:""}}{{sr.t2|default_if_none:""}}+{{sr.m3|default_if_none:""}}{{sr.t3|default_if_none:""}}</td>
      <td>{{ sr.spots }}</td>
      <td>{{ sr.diameter|default_if_none:"" }}</td>
      <td class= 'info ' align="center" valign="middle" >
      {% if sr.imgs %}
      <a target="_blank"href="{{ sr.imgs }}"><img src="{{ sr.imgs }}" style="height: 60px"></a> </td>
      {% else %}
      <a ><img src="/static/img/None.jpg" style="height: 60px"></a>
      {% endif %}
      </td>
      
      
      
      
  </table>        

</div>
<div class= "text-center">
<h3>查询结果<span class="label badge">{{count}}</span></h3>
</div>
<div class="container-fluid">
    <table class="table table-bordered text-center">
    <thead>
      <tr>
        <th class= 'text-center'>设备编号</th>
        <th class= 'warning text-center'>系列</th>
        <th class= 'text-center'>气压MPa</th>
        <th class= 'success text-center'>研磨频次</th>
      </tr>
    </thead>
    {% for sr in search_result %}
    <tr>
      <td >
        <a target="_blank" href="#"
          >{{ sr.equipment }}</a>
      </td>
      <td class = 'warning'>
        <a href="{% url 'r_parts' tool_id=sr.id %}"
          >B-{{ sr.serial }}</a>
      </td>
      <td >
        <a>{{ sr.gauge }}</a>
      </td>
      <td class = 'warning'>
        {{ sr.frequency }}</a>
      </td>
    </tr>
    {% endfor %}
  </table>
{% endif %}
  </div>
  <hr style="border-top:1px dashed #987cb9;" width="100%" color="#987cb9" size=1>

  </div>


  
<nav style="text-align: center;" aria-label="...">
                <ul class="pagination" style="margin-top: 0px">
                    {{ page_html|safe }}
                </ul>
            </nav>
</div>
{% endblock %}

{% block js %}


{% endblock %}

welding/templates/welding/search_result.html
{% extends 'layout/basic.html' %} {% load static %} {% block title %} 首页 
{% endblock %} {% block css %}
<link
  rel="stylesheet"
  href="{% static 'web/plugin/bootstrap/css/bootstrap.css' %}"
/>
<link rel="stylesheet" href="{% static 'web/css/carousel.css' %}" />

{% endblock %} {% block content %}
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

  {% if error_msg %}<div class= "text-center"> {{ error_msg }} </div>
  {% else %}
  {% if request.web.user %}


  {% else %}
                    <div class="bs-example bs-example-standalone" data-example-id="dismissible-alert-js">
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
      <strong><h4>登录警告</h4></strong>
      <p>查看具体参数及产品信息须登录账户方可查询。
      <a target="_blank" href="{% url 'login'  %}"
          >登录</a></p>
        </div>
  {% endif %}



<div class= "text-center">
<h3>查询结果<span class="label badge">{{count}}</span></h3>
</div>

 {% if eq %}
   
   <div class="container-fluid">
    <table class="table table-bordered text-center">
    <thead>
     <tr>        
        <th class= 'active text-center'>线别</th>
        <th class= 'text-center'>设备</th>
        <th class= 'success text-center'>握杆式样</th>
        <th class= 'text-center'>型号</th>
        
      </tr>
    </thead>
    {% for sr in eq %}
    <tr>
      <td class= 'active '>{{ sr.line }}</td>
      <td><a href="{% url 'wsearch_p'  %}">{{ sr.equipment }}</td>
      <td class= 'success '>{{sr.get_etype_display|default_if_none:""}}</td>
      <td>{{ sr.eq_model|default_if_none:"" }}</td>
      
      

    {% endfor %}


  </table>

  </div>


   
 {% else %}    
<div class="container-fluid">
    <table class="table table-bordered text-center">
    <thead>
     <tr>        
        <th class= 'active text-center'>零件号</th>
        <th class= 'text-center'>工序</th>
        <th class= 'success text-center'>焊接内容</th>
        <th class= 'text-center'>打点数</th>
        <th class= 'info text-center'>图示</th>
        <th class= 'text-center'>研磨端径</th>
        <th class= 'text-center'>焊接设备</th>
      </tr>
    </thead>
    {% for sr in search_result %}
    <tr>
      <td class= 'active '>{{ sr.part_no }}</td>
      <td>{{ sr.op }}</td>
      <td class= 'success '>{{sr.m1}}  {{sr.t1}} + {{sr.m2|default_if_none:""}}  {{sr.t2|default_if_none:""}} + {{sr.m3|default_if_none:""}}  {{sr.t3|default_if_none:""}}</td>
      <td>{{ sr.spots|default_if_none:"" }}</td>
      <td class= 'info ' align="center" valign="middle" >
      {% if sr.imgs %}
      <a target="_blank"href="{{ sr.imgs }}"><img src="{{ sr.imgs }}" style="height: 60px"></a> </td>
      {% else %}
      <a ><img src="/static/img/None.jpg" style="height: 60px"></a>
      </td>
      {% endif %}
      <td>{{ sr.diameter|default_if_none:"" }}</td>
      <td>
      <a href="{% url 'wsearch_r' recipe_id=sr.id %}">设备</a></td>

    {% endfor %}


  </table>

  </div>
   {% endif %}  
  <hr style="border-top:1px dashed #987cb9;" width="100%" color="#987cb9" size=1>

  </div>
</div >
  {% endif %}  
<nav style="text-align: center;" aria-label="...">
                <ul class="pagination" style="margin-top: 0px">
                    {{ page_html|safe }}
                </ul>
            </nav>
</div>

{% endblock %}