manuf/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from xadmin.plugins import xversion
import xadmin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    
    #url(r'app01/', include('app01.urls')),
    url(r'^', include('web.urls')),
    url(r'^', include('mould.urls')),
    url(r'^', include('welding.urls')),
    url(r'^', include('testing.urls')),
    url(r'^', include('app01.urls')),
    path('xadmin/', xadmin.site.urls),

]+ static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

web/urls.py
from django.conf.urls import url
from django.conf import settings
from mould.views.resume import resume
from web.views import account, home, project, wiki, file, setting, issues, dashboard, statistics
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    url(r'^register/$', account.register, name='register'),
    url(r'^send/sms/$', account.send_sms, name='send_sms'),
    url(r'^login/$', account.login, name='login'),
    url(r'^account/change/name', account.change_name, name='changename'),
    url(r'^account/changepwd', account.change_pwd, name='changepwd'),
    url(r'^logout/', account.logout, name='logout'),
    url(r'^image/code/', account.image_code, name='image_code'),
    path('', home.index, name='index'),  # 默认首页

    # 项目列表
    url(r'^project/list/', project.project_list, name='project_list'),
    url(r'^project/star/(?P<project_type>\w+)/(?P<project_id>\d+)/$',
        project.project_star, name='project_star'),
    url(r'^project/unstar/(?P<project_type>\w+)/(?P<project_id>\d+)/$',
        project.project_unstar, name='project_unstar'),


    # 项目管理
    # 路由分发
    url(r'^manage/(?P<project_id>\d+)/', include([

        url(r'^wiki/$', wiki.wiki, name='wiki'),
        url(r'^wiki/add/$', wiki.wiki_add, name='wiki_add'),
        url(r'^wiki/delete/(?P<wiki_id>\d+)/$',
            wiki.wiki_delete, name='wiki_delete'),
        url(r'^wiki/edit/(?P<wiki_id>\d+)/$', wiki.wiki_edit, name='wiki_edit'),
        url(r'^wiki/upload/', wiki.wiki_upload, name='wiki_upload'),
        url(r'^wiki/catalog/', wiki.wiki_catalog, name='wiki_catalog'),

        url(r'^file/$', file.file, name='file'),
        url(r'^file/delete/$', file.file_delete, name='file_delete'),
        url(r'^cos/credential/$', file.cos_credential, name='cos_credential'),
        url(r'^file/post/$', file.file_post, name='file_post'),
        url(r'^file/download/(?P<file_id>\d+)/$',
            file.file_download, name='file_download'),

        url(r'^setting/$', setting.setting, name='setting'),
        url(r'^setting/delete/$', setting.setting_delete, name='setting_delete'),

        url(r'^issues/$', issues.issues, name='issues'),
        url(r'^issues/detail/(?P<issues_id>\d+)/$',
            issues.issues_detail, name='issues_detail'),
        url(r'^issues/record/(?P<issues_id>\d+)/$',
            issues.issues_record, name='issues_record'),
        url(r'^issues/change/(?P<issues_id>\d+)/$',
            issues.issues_change, name='issues_change'),
        url(r'^issues/invite/url/$', issues.invite_url, name='invite_url'),

        url(r'^dashboard/$', dashboard.dashboard, name='dashboard'),
        url(r'^dashboard/issues/chart/$',
            dashboard.issues_chart, name='issues_chart'),

        url(r'^statistics/$', statistics.statistics, name='statistics'),
        url(r'^statistics/priority/$', statistics.statistics_priority,
            name='statistics_priority'),
        url(r'^statistics/project/user/$',
            statistics.statistics_project_user, name='statistics_project_user'),

    ], None)),
]

web/models.py
from django.db import models

from datetime import datetime


# Create your models here.
class UserInfo(models.Model):
    # 用户信息

    objects = None
    TEAM_ITEMS = (
        ('T0', '技术组'),
        ('T1', '维修一组'),
        ('T2', '维修二组'),)
    

    username = models.CharField(max_length=30, verbose_name="用户名", unique=True, db_index=True)
    nickname = models.CharField(max_length=4, verbose_name="姓名", null=True, blank=True)
    avatar = models.FileField(upload_to='avatar/', blank='\static\web\img\img_default_avatar.png', null=True, verbose_name="头像")
    password = models.CharField(verbose_name="密码", max_length=32)
    email = models.EmailField(max_length=254, verbose_name="邮箱")
    team = models.CharField(max_length=2, choices=TEAM_ITEMS, default="T0", verbose_name="组别")
    mobile_phone = models.CharField(blank=True, null=True, max_length=11, verbose_name="手机")
    work_id = models.CharField(max_length=5, verbose_name="工号", null=True, blank=True)
    is_active = models.BooleanField(default=False, verbose_name="激活状态")
    is_staff = models.BooleanField(default=True, verbose_name="是否是员工")
    date_joined = models.DateTimeField(default=datetime.now, verbose_name="加入时间")
    subscribe = models.BooleanField(default=False)



class PricePolicy(models.Model):
    """
    价格策略
    """
    category_choices = {
        (1, '免费版'),
        (2, '收费版'),
        (3, '其他'),
    }

    category = models.SmallIntegerField(verbose_name='收费类型', default=2, choices=category_choices)
    title = models.CharField(verbose_name='标题', max_length=32)
    price = models.PositiveIntegerField(verbose_name='价格')

    project_num = models.PositiveIntegerField(verbose_name='项目数')
    project_member = models.PositiveIntegerField(verbose_name='项目成员')
    project_space = models.PositiveIntegerField(verbose_name='单项目空间', help_text='G')
    per_file_size = models.PositiveIntegerField(verbose_name='单文件大小', help_text='M')

    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)


class Transaction(models.Model):
    """
    交易记录
    """
    status_choice = {
        (1, '未支付'),
        (2, '已支付')
    }

    status = models.SmallIntegerField(verbose_name='状态', choices=status_choice)

    order = models.CharField(verbose_name='订单号', max_length=64, unique=True)  # 唯一索引

    user = models.ForeignKey(verbose_name='用户', on_delete=models.CASCADE, to='UserInfo')
    price_policy = models.ForeignKey(verbose_name='价格策略', on_delete=models.CASCADE, to='PricePolicy')

    count = models.IntegerField(verbose_name='数量(年)', help_text='0表示无限期')

    price = models.IntegerField(verbose_name='实际支付价格')

    start_datetime = models.DateTimeField(verbose_name='开始时间', null=True, blank=True)
    end_datetime = models.DateTimeField(verbose_name='结束时间', null=True, blank=True)

    create_datetime = models.DateTimeField(verbose_name='结束时间', auto_now_add=True)




class Project(models.Model):
    """
    项目表
    """
    COLOR_CHOICES = {
        (1, '#56b8eb'),
        (2, '#f28033'),
        (3, '#ebc656'),
        (4, '#a2d148'),
        (5, '#20bFA4'),
        (6, '#7461c2'),
        (7, '#20bfa3'),
    }

    name = models.CharField(verbose_name='项目名', max_length=32)
    color = models.SmallIntegerField(verbose_name='颜色', choices=COLOR_CHOICES, default=1)
    desc = models.CharField(verbose_name='项目描述', max_length=255, null=True, blank=True)
    user_space = models.BigIntegerField(verbose_name='项目已使用空间', default=0, help_text='字节')
    star = models.BooleanField(verbose_name='星标', default=False)

    join_count = models.SmallIntegerField(verbose_name='参与人数', default=1)
    creator = models.ForeignKey(verbose_name='创建者', on_delete=models.CASCADE, to='UserInfo')
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)


class ProjectUser(models.Model):
    """
    项目参与者
    """
    user = models.ForeignKey(verbose_name='用户', on_delete=models.CASCADE, to='UserInfo', related_name='projects')

    project = models.ForeignKey(verbose_name='项目', on_delete=models.CASCADE, to='Project')

    invitee = models.ForeignKey(verbose_name='邀请人', on_delete=models.CASCADE, to='UserInfo',
                                related_name='invites', null=True, blank=True)

    star = models.BooleanField(verbose_name='星标', default=False)

    create_datetime = models.DateTimeField(verbose_name='加入时间', auto_now_add=True)


class Wiki(models.Model):
    project = models.ForeignKey(verbose_name='项目', on_delete=models.CASCADE, to='Project')
    title = models.CharField(verbose_name='标题', max_length=32)
    content = models.TextField(verbose_name='内容')
    depth = models.IntegerField(verbose_name='深度', default=1)

    # 自关联
    parent = models.ForeignKey(verbose_name='父文章', to='Wiki', on_delete=models.CASCADE,
                               null=True, blank=True, related_name='children')

    def __str__(self):
        return self.title


class FileRepository(models.Model):
    """文件库对象"""
    project = models.ForeignKey(verbose_name='项目', on_delete=models.CASCADE, to='Project')
    file_type_choices = {
        (1, '文件'),
        (2, '文件夹')
    }
    file_type = models.SmallIntegerField(verbose_name='类型', choices=file_type_choices)
    name = models.CharField(verbose_name='文件夹名称', max_length=32, help_text="文件/文件夹名")
    key = models.CharField(verbose_name='文件存储在COS中的KEY', max_length=128, null=True, blank=True)
    file_size = models.BigIntegerField(verbose_name='文件大小', null=True, blank=True, help_text='字节')
    file_path = models.CharField(verbose_name='文件路径', max_length=255, null=True, blank=True)

    parent = models.ForeignKey(verbose_name='父级目录', to='self', on_delete=models.CASCADE,
                               related_name='child', null=True, blank=True)

    update_user = models.ForeignKey(verbose_name='最近更新者', on_delete=models.CASCADE, to='UserInfo')
    update_datetime = models.DateTimeField(verbose_name='更新时间', auto_now=True)


class Issues(models.Model):
    """问题"""
    project = models.ForeignKey(verbose_name='项目', on_delete=models.CASCADE, to='Project')
    issues_type = models.ForeignKey(verbose_name='问题类型', on_delete=models.CASCADE, to='IssuesType')
    module = models.ForeignKey(verbose_name='模块', on_delete=models.CASCADE, to='Module', null=True, blank=True)

    subject = models.CharField(verbose_name='主题', max_length=80)
    desc = models.TextField(verbose_name='问题描述')
    priority_choices = {
        ("danger", "高"),
        ("warning", "中"),
        ("success", "低"),
    }
    priority = models.CharField(verbose_name='优先级', max_length=12, choices=priority_choices, default='danger')

    # 新建/处理中/已解决/已忽略/待反馈/已关闭/重新打开
    status_choices = {
        (1, '新建'),
        (2, '处理中'),
        (3, '已解决'),
        (4, '已忽略'),
        (5, '待反馈'),
        (6, '已关闭'),
        (7, '重新打开'),
    }
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choices, default=1)

    assign = models.ForeignKey(verbose_name='指派', on_delete=models.CASCADE, to='UserInfo',
                               related_name='task', null=True, blank=True)
    attention = models.ManyToManyField(verbose_name='关注者', to='UserInfo', related_name='observe', blank=True)

    start_date = models.DateField(verbose_name='开始时间', null=True, blank=True)
    end_date = models.DateField(verbose_name='结束时间', null=True, blank=True)

    mode_choices = {
        (1, '公开模式'),
        (2, '隐私模式'),
    }
    mode = models.SmallIntegerField(verbose_name='模式', choices=mode_choices, default=1)

    parent = models.ForeignKey(verbose_name='父问题', to='self', related_name='child', null=True, blank=True,
                               on_delete=models.SET_NULL)

    creator = models.ForeignKey(verbose_name='创建者', on_delete=models.CASCADE, to='UserInfo',
                                related_name='create_problems')

    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    latest_update_datetime = models.DateTimeField(verbose_name='创建时间', auto_now=True)

    def __str__(self):
        return self.subject


class Module(models.Model):
    """模块(里程碑)"""
    project = models.ForeignKey(verbose_name='项目', on_delete=models.CASCADE, to='Project')
    title = models.CharField(verbose_name='模块名称', max_length=32)

    def __str__(self):
        return self.title


class IssuesType(models.Model):
    """问题类型 例如：任务，功能，Bug"""

    PROJECT_INIT_LIST = ["任务", "功能", "Bug"]

    title = models.CharField(verbose_name='类型名称', max_length=32)
    project = models.ForeignKey(verbose_name='项目', on_delete=models.CASCADE, to='Project')

    def __str__(self):
        return self.title


class IssuesReply(models.Model):
    """ 问题回复"""

    reply_type_choices = (
        (1, '修改记录'),
        (2, '回复')
    )
    reply_type = models.IntegerField(verbose_name='类型', choices=reply_type_choices)

    issues = models.ForeignKey(verbose_name='问题', on_delete=models.CASCADE, to='Issues')
    content = models.TextField(verbose_name='描述')
    creator = models.ForeignKey(verbose_name='创建者', on_delete=models.CASCADE, to='UserInfo',
                                related_name='create_reply')
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    reply = models.ForeignKey(verbose_name='回复', on_delete=models.CASCADE, to='self', null=True, blank=True)


class ProjectInvite(models.Model):
    """ 项目邀请码 """
    project = models.ForeignKey(verbose_name='项目', on_delete=models.CASCADE, to='Project')
    code = models.CharField(verbose_name='邀请码', max_length=64, unique=True)
    count = models.PositiveIntegerField(verbose_name='限制数量', null=True, blank=True, help_text='空表示无数量限制')
    use_count = models.PositiveIntegerField(verbose_name='已邀请数量', default=0)
    period_choices = (
        (30, '30分钟'),
        (60, '1小时'),
        (300, '5小时'),
        (1440, '24小时'),
    )
    period = models.IntegerField(verbose_name='有效期', choices=period_choices, default=1440)
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

web/forms/wiki.py
from web import models
from django import forms
from web.forms.bootstrap import BootStrapForm


class WikiModelForm(BootStrapForm, forms.ModelForm):
    class Meta:
        model = models.Wiki
        exclude = ['project', 'depth',]

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # 找到想要的字段，将数据重置
        total_data_list = [('', '--------'), ]
        data_list = models.Wiki.objects.filter(project=request.web.project).values_list('id', 'title')
        total_data_list.extend(data_list)

        self.fields['parent'].choices = total_data_list

testing/views/dashboard.py
import json
import datetime

from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from web import models
from web.forms.issues import IssuesModelForm, IssuesReplyModelForm, IssuesInviteModelForm
from utils.encrypt import uid
from django.utils.safestring import mark_safe
from utils.pagination import Pagination


def die_list(request):
    context={}
    pass
    return render(request, 'testing/dashboard.html', context)

web/views/dashboard.py
import datetime
import time

from django.http import JsonResponse
from django.shortcuts import render
import collections
from web import models
from django.db.models import Count


def dashboard(request, project_id):
    """概览"""
    # 项目状态
    status_dict = collections.OrderedDict()

    for key, text in sorted(models.Issues.status_choices):
        status_dict[key] = {'text': text, 'count': 0}

    issues_data = models.Issues.objects.filter(project_id=project_id).values('status').annotate(ct=Count('id'))

    for item in issues_data:
        status_dict[item['status']]['count'] = item['ct']

    join_user = models.ProjectUser.objects.filter(project_id=project_id).values_list('user_id', 'user__nickname')

    top_ten = models.Issues.objects.filter(project_id=project_id, assign__isnull=False).order_by('-id')[0:10]

    context = {
        'status_dict': status_dict,
        'join_user': join_user,
        'top_ten': top_ten
    }
    print(join_user)
    return render(request, 'web/dashboard.html', context)


def issues_chart(request, project_id):
    """ 在概览页面生成highcharts所需的数据 """
    today = datetime.datetime.now().date()
    date_dict = collections.OrderedDict()
    for i in range(0, 30):
        date = today - datetime.timedelta(days=i)
        date_dict[date.strftime("%Y-%m-%d")] = [time.mktime(date.timetuple()) * 1000, 0]

    # select xxxx,1 as ctime from xxxx
    # select id,name,email from table;
    # select id,name, strftime("%Y-%m-%d",create_datetime) as ctime from table;
    # "DATE_FORMAT(web_transaction.create_datetime,'%%Y-%%m-%%d')"
    result = models.Issues.objects.filter(project_id=project_id,
                                          create_datetime__gte=today - datetime.timedelta(days=30)).extra(
        select={'ctime': "strftime('%%Y-%%m-%%d',web_issues.create_datetime)"}).values('ctime').annotate(ct=Count('id'))

    for item in result:
        date_dict[item['ctime']][1] = item['ct']

    return JsonResponse({'status': True, 'data': list(date_dict.values())})

web/views/setting.py
from django.shortcuts import render, redirect

#from utils.tencent.cos import delete_bucket
from web import models


def setting(request, project_id):
    return render(request, 'web/setting.html')


def setting_delete(request, project_id):
    """删除项目"""
    if request.method == 'GET':
        return render(request, 'web/setting_delete.html')

    project_name = request.POST.get('project_name')
    if not project_name or project_name != request.web.project.name:
        return render(request, 'web/setting_delete.html', {'error': "项目名称错误"})

    # 删除项目(只有项目创建者才能删除）
    if request.web.user != request.web.project.creator:
        return render(request, 'web/setting_delete.html', {'error': "只有项目创建者才能删除项目"})

    # 删除桶里面所有文件
    # 删除桶
    #delete_bucket(request.web.project.bucket, request.web.project.region)

    # 删除项目
    models.Project.objects.filter(id=request.web.project.id).delete()

    return redirect("project_list")

web/templates/web/change.html
{% extends 'layout/basic.html' %}

{% block title %}{{ page_title }}{% endblock %}
{% block nav_home_active %}active{% endblock %}
{% block content %}
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ form_title }}</h3>
                    </div>
                    {% if oldpassword_is_wrong %}
                        <div class="alert alert-error">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <h4>错误!</h4>原密码不正确
                        </div>
                    {% endif %}

                    <div class="panel-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                {% if not field.is_hidden %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {% endif %}
                                {{ field }}
                                <p class="text-danger">{{ field.errors.as_text }}</p>
                            {% endfor %}
                            <span id="tip" class="text-danger">{{ form.non_field_errors }}</span>
                            <div class="clearfix"></div>
                            <div class="pull-left">
                                {% block other_buttons %}{% endblock %}
                            </div>
                            <div class="pull-right">
                                <input type="submit" value="{{ submit_text }}" class="btn btn-primary">
                                <button class="btn btn-default" onclick="window.location.href='{{ return_back_url }}'">返回</button>
                            </div>

                        </form>
                    </div>
                </div>            
            </div>
        </div>
    </div>    
{% endblock %}

web/templates/web/changename.html
{% extends 'layout/basic.html' %}

{% block title %}{{ page_title }}{% endblock %}
{% block nav_home_active %}active{% endblock %}
{% block content %}
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ form_title }}</h3>
                    </div>
                    <div class="panel-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                {% if not field.is_hidden %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {% endif %}
                                {{ field }}
                                <p class="text-danger">{{ field.errors.as_text }}</p>
                            {% endfor %}
                            <span id="tip" class="text-danger">{{ form.non_field_errors }}</span>
                            <div class="clearfix"></div>
                            <div class="pull-left">
                                {% block other_buttons %}{% endblock %}
                            </div>
                            <div class="pull-right">
                                <input type="submit" value="{{ submit_text }}" class="btn btn-primary">
                                <button class="btn btn-default" onclick="window.location.href='{{ return_back_url }}'">返回</button>
                            </div>
                            
                        </form>
                    </div>
                </div>            
            </div>
        </div>
    </div>    
{% endblock %}

web/templates/web/login_sms.html
{% extends "layout/basic.html" %}
{% load static %}

{% block title %} 用户短信登陆 {% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'web/css/account.css' %}">
    <style>
        .error-msg {
            color: red;
            position: absolute;
            font-size: 13px;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="account">
        <h1 style="text-align: center">用户短信登陆</h1>
        <form id="smsForm" method="POST" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="clearfix">
                            <div class="col-md-6" style="padding-left: 0px">{{ field }}
                                <span class="error-msg"></span>
                            </div>
                            <div class="col-md-6"><input id="btnSms" type="button" class="btn btn-default"
                                                         value="点击获取验证码"></div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="error-msg"></span>
                    </div>
                {% endif %}
            {% endfor %}
            <div>
                <div style="float:right">
                    <a href="{% url 'login' %}">用户名密码登陆？</a>
                </div>
            </div>
            <input id="btnSubmit" type="button" class="btn btn-primary" value="登  陆">
        </form>
    </div>
{% endblock %}


{% block js %}
    <script>
        //页面框架加载完成自动执行
        $(function () {
            bindClickBtnSms();
            bindClickBtnSubmit();
        });

        /*
        * 点击登陆提交
        * */
        function bindClickBtnSubmit() {
            $('#btnSubmit').click(function () {
                $('.error-msg').empty();
                //收集表单数据 $('#regForm').serialize()
                //获取所有字段数据+csrf_token
                //数据ajax传到后台
                $.ajax({
                    url: "{% url 'login_sms' %}",
                    type: "POST",
                    data: $('#smsForm').serialize(),
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            location.href = res.data;
                        } else {
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }


        /*
        * 点击获取验证码的按钮绑定事件
        * */
        function bindClickBtnSms() {
            $('#btnSms').click(function () {
                $(".error-msg").empty();

                //获取用户手机号
                //找到手机号输入框的ID，根据ID获取值
                var mobile_Phone = $('#id_mobile_phone').val();


                //发送ajax请求，把手机号发送过去
                $.ajax({
                    url: "{% url 'send_sms' %}",
                    type: "GET",
                    data: {
                        mobile_phone: mobile_Phone,
                        tpl: "login"
                    },
                    dataType: "JSON",
                    success: function (res) {
                        //ajax请求发送成功之后，自动执行的函数
                        if (res.status) {
                            sendSmsRemind();
                        } else {
                            //{status:False,error:{mobile_phone:['错误信息',]}}
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }

        /*
        * 请求成功，计时器开始
        * */
        function sendSmsRemind() {
            var $smsBtn = $('#btnSms');
            $smsBtn.prop('disabled', true);//禁用

            var time = 59;
            var remind = setInterval(function () {
                $smsBtn.val(time + '秒重新发送');
                time = time - 1;
                if (time < 1) {
                    clearInterval();
                    $smsBtn.val('点击获取验证码').prop('disabled', false);
                }
            }, 1000);
        }

    </script>
{% endblock %}

web/templates/web/register.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %} 用户注册 {% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'web/css/account.css' %}">
    <style>
        .error-msg {
            color: red;
            position: absolute;
            font-size: 13px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="account">
        <h1 style="text-align: center">用户注册</h1>
        <form id="regForm" method="POST" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="clearfix">
                            <div class="col-md-6" style="padding-left: 0px">{{ field }}
                                <span class="error-msg"></span>
                            </div>
                            <div class="col-md-6"><input id="btnSms" type="button" class="btn btn-default"
                                                         value="点击获取验证码"></div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="error-msg"></span>
                    </div>
                {% endif %}
            {% endfor %}
            <input id="btnSubmit" type="button" class="btn btn-primary" value="注  册">
        </form>
    </div>
{% endblock %}


 {% block js %}
    <script>
        //页面框架加载完成自动执行
        $(function () {
            bindClickBtnSms();
            bindClickBtnSubmit();
        });

        /*
        * 点击注册提交
        * */
        function bindClickBtnSubmit() {
            $('#btnSubmit').click(function () {
                $('.error-msg').empty();
                //收集表单数据 $('#regForm').serialize()
                //获取所有字段数据+csrf_token
                //数据ajax传到后台
                $.ajax({
                    url: "{% url 'register' %}",
                    type: "POST",
                    data: $('#regForm').serialize(),
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            location.href = res.data;
                        } else {
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }


        /*
        * 点击获取验证码的按钮绑定事件
        * */
        function bindClickBtnSms() {
            $('#btnSms').click(function () {
                $(".error-msg").empty();

                //获取用户手机号
                //找到手机号输入框的ID，根据ID获取值
                var mobile_Phone = $('#id_mobile_phone').val();
                var nick_Name = $('#id_nickname').val();


                //发送ajax请求，把手机号发送过去
                $.ajax({
                    url: "{% url 'send_sms' %}",
                    type: "GET",
                    data: {
                        mobile_phone: mobile_Phone,
                        tpl: "register",
                        nickname: nick_Name,
                    },
                    dataType: "JSON",
                    success: function (res) {
                        //ajax请求发送成功之后，自动执行的函数
                        if (res.status) {
                            sendSmsRemind();
                        } else {
                            //{status:False,error:{mobile_phone:['错误信息',]}}
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }

        /*
        * 请求成功，计时器开始
        * */
        function sendSmsRemind() {
            var $smsBtn = $('#btnSms');
            $smsBtn.prop('disabled', true);//禁用

            var time = 59;
            var remind = setInterval(function () {
                $smsBtn.val(time + '秒重新发送');
                time = time - 1;
                if (time < 1) {
                    clearInterval();
                    $smsBtn.val('点击获取验证码').prop('disabled', false);
                }
            }, 1000);
        }

    </script>
{% endblock %}